# -*- coding: utf-8 -*-
"""Analisis_Completo_Zomato.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHUqesDbKNVpSBb7ab_Ep09QVNF8pFo8

# Análisis Completo de Restaurantes Zomato
## Aprendizaje No Supervisado + Aprendizaje Supervisado

**Dataset:** Zomato Clean CSV  
**Objetivo:** Primero descubrir segmentos naturales de restaurantes (clustering), luego predecir la calificación (rate) con modelos de regresión, y comparar los resultados de ambos enfoques.

| Sección | Técnica |
|---|---|
| 1–9 | Aprendizaje **no supervisado** (PCA + K-Means + Jerárquico) |
| 10–13 | Aprendizaje **supervisado** (Ridge Regression + Random Forest) |
| 14 | **Comparación cruzada** de ambos enfoques |

## 1. Importaciones y configuración

Importamos todas las librerías necesarias para los dos enfoques en un único bloque.
"""

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ── No supervisado ──────────────────────────────────────────────────────────
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import (silhouette_score, calinski_harabasz_score,
                             davies_bouldin_score, silhouette_samples)
from scipy.cluster.hierarchy import dendrogram, linkage

# ── Supervisado ─────────────────────────────────────────────────────────────
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8')
np.random.seed(42)
RANDOM_STATE = 42

print('Librerías cargadas correctamente.')

"""## 2. Carga y preparación de datos

Cargamos el dataset limpio proveniente del Parcial 1. Este CSV ya tiene:
- **Count Encoding** para columnas de alta cardinalidad (`cuisines`, `location`, `rest_type`).
- **One-Hot Encoding** para columnas de baja cardinalidad (`online_order`, `book_table`).

"""

df = pd.read_csv('zomato_clean.csv', on_bad_lines='skip')
print('Shape del dataset:', df.shape)
print('Columnas disponibles:')
print(df.columns.tolist())
df.head()

"""## 3. Preparación de features para clustering

El modelo **no supervisado** no usa la columna `rate` (calificación) como variable objetivo —
el algoritmo tiene que encontrar patrones por su cuenta sin saber las calificaciones.

"""

def preparar_features(df):
    excluir = [
        'rate',
        'name', 'location', 'rest_type', 'cuisines',
        'listed_in(type)', 'listed_in(city)',
        'online_order', 'book_table',
    ]
    num_cols = df.select_dtypes(include=['number']).columns.tolist()
    feature_cols = [c for c in num_cols if c not in excluir]

    print(f'Features seleccionadas ({len(feature_cols)}): {feature_cols}')
    data = df[feature_cols].copy()
    data = data.fillna(data.median(numeric_only=True))
    return data

X_cluster = preparar_features(df)
print(f'\nShape de X_cluster: {X_cluster.shape}')
print('Columnas con count encoding:', [c for c in X_cluster.columns if '_count' in c])

"""## 4. Reducción de dimensionalidad con PCA

**¿Por qué PCA?** Reducir dimensiones elimina ruido, mejora la velocidad del clustering
y permite visualizar los grupos en 2D. Se retiene el **95% de la varianza**.

"""

pipeline_pca = Pipeline([
    ('scaler', StandardScaler()),
    ('pca',    PCA(n_components=0.95, random_state=RANDOM_STATE))
])

X_pca = pipeline_pca.fit_transform(X_cluster)
varianza_acumulada = np.cumsum(pipeline_pca.named_steps['pca'].explained_variance_ratio_)

print(f'Dimensiones originales : {X_cluster.shape[1]}')
print(f'Componentes PCA (95 %v): {X_pca.shape[1]}')

plt.figure(figsize=(9, 4))
plt.plot(varianza_acumulada, color='steelblue', lw=2)
plt.axhline(0.95, color='red', linestyle='--', label='95% varianza')
plt.xlabel('Número de componentes principales')
plt.ylabel('Varianza explicada acumulada')
plt.title('PCA — Varianza explicada acumulada')
plt.legend()
plt.tight_layout()
plt.show()

"""## 5. K-Means — Elección del número de clusters (k)

Probamos k de 2 a 10 y medimos:
- **Inercia**: compacidad interna de los grupos (queremos que baje).
- **Silhouette Score**: qué tan bien separados están los grupos (queremos que suba).

"""

rango_k = range(2, 11)
inercias    = []
silhouettes = []

for k in rango_k:
    km = KMeans(n_clusters=k, init='k-means++', n_init=10, random_state=RANDOM_STATE)
    labels = km.fit_predict(X_pca)
    inercias.append(km.inertia_)
    silhouettes.append(silhouette_score(X_pca, labels))

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
axes[0].plot(list(rango_k), inercias, 'o-', color='steelblue', lw=2)
axes[0].set_xlabel('Número de clusters (k)')
axes[0].set_ylabel('Inercia')
axes[0].set_title('Elbow Curve — Inercia')
axes[0].grid(True, alpha=0.3)

axes[1].plot(list(rango_k), silhouettes, 'o-', color='darkorange', lw=2)
axes[1].set_xlabel('Número de clusters (k)')
axes[1].set_ylabel('Silhouette Score')
axes[1].set_title('Silhouette Score por k')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print('k     Inercia       Silhouette')
for k, in_, sil in zip(rango_k, inercias, silhouettes):
    print(f'k={k}   {in_:>12.1f}   {sil:.4f}')

"""## 6. K-Means — Optimización de hiperparámetros

- **GridSearchCV**: prueba todas las combinaciones exactas de la grilla.
- **RandomizedSearchCV**: muestrea combinaciones al azar (más rápido en espacios grandes).

Se comparan los mejores resultados de cada búsqueda y se elige el de mayor Silhouette.

"""

def silhouette_scorer(estimator, X):
    labels = estimator.fit_predict(X)
    if len(set(labels)) < 2:
        return -1.0
    return silhouette_score(X, labels, random_state=RANDOM_STATE)

param_grid = {
    'n_clusters': list(range(3, 9)),
    'init':       ['k-means++', 'random'],
    'n_init':     [10, 20],
    'max_iter':   [300, 500],
    'algorithm':  ['lloyd', 'elkan']
}

kmeans_base = KMeans(random_state=RANDOM_STATE)

print('Iniciando GridSearchCV...')
grid_search = GridSearchCV(
    estimator=kmeans_base, param_grid=param_grid,
    scoring=silhouette_scorer, cv=3, n_jobs=-1, verbose=0
)
grid_search.fit(X_pca)
print(f'  Mejor Silhouette (GridSearch):      {grid_search.best_score_:.4f}')
print(f'  Mejores parámetros:                 {grid_search.best_params_}')

print('\nIniciando RandomizedSearchCV...')
rand_search = RandomizedSearchCV(
    estimator=kmeans_base, param_distributions=param_grid,
    n_iter=20, scoring=silhouette_scorer, cv=3,
    random_state=RANDOM_STATE, n_jobs=-1, verbose=0
)
rand_search.fit(X_pca)
print(f'  Mejor Silhouette (RandomizedSearch): {rand_search.best_score_:.4f}')
print(f'  Mejores parámetros:                  {rand_search.best_params_}')

if grid_search.best_score_ >= rand_search.best_score_:
    best_kmeans  = grid_search.best_estimator_
    best_params  = grid_search.best_params_
    best_score   = grid_search.best_score_
    metodo_ganador = 'GridSearchCV'
else:
    best_kmeans  = rand_search.best_estimator_
    best_params  = rand_search.best_params_
    best_score   = rand_search.best_score_
    metodo_ganador = 'RandomizedSearchCV'

print(f'\nModelo seleccionado: {metodo_ganador} (Silhouette={best_score:.4f})')

"""## 7. Evaluación del modelo K-Means óptimo

Medimos tres métricas complementarias y visualizamos los clusters en el espacio PCA (PC1 vs PC2).

"""

labels_kmeans = best_kmeans.predict(X_pca)
k_opt = len(np.unique(labels_kmeans))

sil_km = silhouette_score(X_pca, labels_kmeans)
ch_km  = calinski_harabasz_score(X_pca, labels_kmeans)
db_km  = davies_bouldin_score(X_pca, labels_kmeans)

print(f'Métricas del modelo K-Means final (k={k_opt})')
print(f'  Silhouette Score  : {sil_km:.4f}  (↑ mejor)')
print(f'  Calinski-Harabasz : {ch_km:.2f}  (↑ mejor)')
print(f'  Davies-Bouldin    : {db_km:.4f}  (↓ mejor)')
print(f'  Inercia           : {best_kmeans.inertia_:.2f}')

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

sc = axes[0].scatter(X_pca[:, 0], X_pca[:, 1], c=labels_kmeans,
                     cmap='tab10', s=20, alpha=0.7)
plt.colorbar(sc, ax=axes[0], label='Cluster')
axes[0].set_xlabel('PC1'); axes[0].set_ylabel('PC2')
axes[0].set_title(f'K-Means (k={k_opt}) — Silhouette: {sil_km:.4f}')
axes[0].grid(True, alpha=0.3)

sil_vals = silhouette_samples(X_pca, labels_kmeans)
y_lower = 10
for i in range(k_opt):
    cluster_sil = np.sort(sil_vals[labels_kmeans == i])
    size = cluster_sil.shape[0]
    y_upper = y_lower + size
    color = plt.cm.tab10(i / k_opt)
    axes[1].fill_betweenx(np.arange(y_lower, y_upper), 0, cluster_sil,
                           facecolor=color, edgecolor=color, alpha=0.7)
    axes[1].text(-0.05, y_lower + 0.5 * size, str(i))
    y_lower = y_upper + 10

axes[1].axvline(sil_km, color='red', linestyle='--', label=f'Media={sil_km:.4f}')
axes[1].set_xlabel('Silhouette Coefficient')
axes[1].set_title('Silhouette plot por cluster (K-Means)')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 8. Clustering Jerárquico

El **Agglomerative Clustering** (método Ward) no requiere definir k a priori.  
Usamos el mismo k óptimo encontrado por K-Means para poder comparar directamente.

"""

np.random.seed(RANDOM_STATE)
idx_muestra = np.random.choice(len(X_pca), size=500, replace=False)
X_muestra = X_pca[idx_muestra]

linkage_matrix = linkage(X_muestra, method='ward')

plt.figure(figsize=(14, 5))
dendrogram(
    linkage_matrix,
    truncate_mode='lastp', p=20,
    show_leaf_counts=True, leaf_rotation=90, leaf_font_size=9,
    color_threshold=0.7 * max(linkage_matrix[:, 2])
)
plt.title('Dendrograma — Clustering Jerárquico (Ward, muestra=500)')
plt.xlabel('Índice de muestra (o tamaño del cluster)')
plt.ylabel('Distancia')
plt.tight_layout()
plt.show()

agg = AgglomerativeClustering(n_clusters=k_opt, linkage='ward')
labels_agg = agg.fit_predict(X_pca)

sil_agg = silhouette_score(X_pca, labels_agg)
ch_agg  = calinski_harabasz_score(X_pca, labels_agg)
db_agg  = davies_bouldin_score(X_pca, labels_agg)

print(f'Métricas Clustering Jerárquico (k={k_opt})')
print(f'  Silhouette Score  : {sil_agg:.4f}  (↑ mejor)')
print(f'  Calinski-Harabasz : {ch_agg:.2f}  (↑ mejor)')
print(f'  Davies-Bouldin    : {db_agg:.4f}  (↓ mejor)')

plt.figure(figsize=(7, 5))
sc2 = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=labels_agg,
                  cmap='tab10', s=20, alpha=0.7)
plt.colorbar(sc2, label='Cluster')
plt.xlabel('PC1'); plt.ylabel('PC2')
plt.title(f'Clustering Jerárquico (Ward, k={k_opt}) — Silhouette: {sil_agg:.4f}')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""## 9. Comparación: K-Means vs Clustering Jerárquico

"""

metricas_ns = pd.DataFrame({
    'Método':             ['K-Means', 'Jerárquico (Ward)'],
    'Silhouette Score':   [round(sil_km, 4),  round(sil_agg, 4)],
    'Calinski-Harabasz':  [round(ch_km, 2),   round(ch_agg, 2)],
    'Davies-Bouldin':     [round(db_km, 4),   round(db_agg, 4)],
}).set_index('Método')

print(metricas_ns.to_string())

fig, axes = plt.subplots(1, 3, figsize=(13, 4))
metodos = ['K-Means', 'Jerárquico']
colores = ['steelblue', 'darkorange']

for ax, col, mejor_dir in zip(axes,
                               ['Silhouette Score', 'Calinski-Harabasz', 'Davies-Bouldin'],
                               ['↑', '↑', '↓']):
    vals = metricas_ns[col].values
    ax.bar(metodos, vals, color=colores)
    ax.set_title(f'{col} ({mejor_dir} mejor)')
    ax.set_ylabel(col)
    for i, v in enumerate(vals):
        ax.text(i, v * 0.98, f'{v}', ha='center', va='top',
                fontsize=9, color='white', fontweight='bold')

plt.suptitle(f'Comparación de métodos de clustering (k={k_opt})', y=1.02)
plt.tight_layout()
plt.show()

"""## 10. Perfil de segmentos (K-Means óptimo)

Agregamos las etiquetas de cluster al dataframe original y calculamos el perfil medio de cada grupo.  
Este perfil es la "descripción" de cada segmento: qué características comparten sus restaurantes.

"""

df_seg = df.copy()
df_seg['cluster'] = labels_kmeans

num_cols_seg = df_seg.select_dtypes(include='number').columns.drop(['cluster'], errors='ignore')
perfil = df_seg.groupby('cluster')[num_cols_seg].mean().round(3)
distribucion = df_seg['cluster'].value_counts().sort_index().rename('n_restaurantes')

print('=== PERFIL DE SEGMENTOS DE RESTAURANTES ===')
print(perfil)
print('\nDistribución:')
print(distribucion)

plt.figure(figsize=(6, 4))
distribucion.plot(kind='bar', color='steelblue', edgecolor='black')
plt.xlabel('Cluster'); plt.ylabel('Número de restaurantes')
plt.title('Distribución de restaurantes por cluster (K-Means)')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""---
# Parte II — Aprendizaje Supervisado

A partir de aquí entrenamos modelos de **regresión** para predecir la calificación (`rate`) de cada restaurante.  
A diferencia del clustering, aquí sí usamos `rate` como **variable objetivo** (target) y le damos al modelo ejemplos con la respuesta correcta para que aprenda.

| Modelo | Tipo | Búsqueda de hiperparámetros |
|---|---|---|
| Ridge Regression | Lineal regularizado | GridSearchCV |
| Random Forest | Ensemble de árboles | RandomizedSearchCV |

## 11. Preparación de datos para regresión

Usamos un subconjunto de features más interpretables para el modelo supervisado,
incluyendo variables categóricas que el pipeline procesará con OneHotEncoder.  
Dividimos en 80% entrenamiento y 20% prueba con `train_test_split`.
"""

features_sup = ['online_order_Yes', 'book_table_Yes',
                'approx_cost(for two people)', 'votes',
                'location', 'listed_in(type)']
target = 'rate'

df_sup = df[features_sup + [target]].dropna()

X_sup = df_sup[features_sup]
y_sup = df_sup[target]

X_train, X_test, y_train, y_test = train_test_split(
    X_sup, y_sup, test_size=0.2, random_state=RANDOM_STATE
)

print(f'Registros para entrenamiento : {len(X_train)}')
print(f'Registros para prueba        : {len(X_test)}')
print(f'\nDistribución del target (rate):')
print(y_sup.describe().round(3))

"""## 12. Pipelines y búsqueda de hiperparámetros

Un **Pipeline** encadena el preprocesamiento y el modelo en un solo objeto.  
Esto garantiza que el escalado y encoding se aprenda solo en los datos de entrenamiento
y se aplique correctamente en los datos de prueba.

"""

numeric_features_sup  = ['approx_cost(for two people)', 'votes', 'online_order_Yes', 'book_table_Yes']
categorical_features_sup = ['location', 'listed_in(type)']

preprocessor_sup = ColumnTransformer(transformers=[
    ('num', StandardScaler(), numeric_features_sup),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_sup)
])

# ── Modelo A: Ridge Regression ───────────────────────────────────────────────
pipe_ridge = Pipeline(steps=[
    ('preprocessor', preprocessor_sup),
    ('regressor', Ridge())
])

param_grid_ridge = {'regressor__alpha': [0.1, 1.0, 10.0, 100.0]}
grid_search_ridge = GridSearchCV(pipe_ridge, param_grid_ridge,
                                  cv=5, scoring='r2', n_jobs=-1)

# ── Modelo B: Random Forest ──────────────────────────────────────────────────
pipe_rf = Pipeline(steps=[
    ('preprocessor', preprocessor_sup),
    ('regressor', RandomForestRegressor(random_state=RANDOM_STATE))
])

param_dist_rf = {
    'regressor__n_estimators':    [50, 100, 200],
    'regressor__max_depth':       [None, 10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10]
}
random_search_rf = RandomizedSearchCV(pipe_rf, param_distributions=param_dist_rf,
                                       n_iter=5, cv=3, scoring='r2',
                                       random_state=RANDOM_STATE, n_jobs=-1)

print('Optimizando Ridge Regression...')
grid_search_ridge.fit(X_train, y_train)

print('Optimizando Random Forest...')
random_search_rf.fit(X_train, y_train)

print('\nEntrenamiento completado.')

"""## 13. Evaluación de modelos supervisados

Evaluamos en el **conjunto de prueba** (datos que el modelo nunca vio durante el entrenamiento).  
Las métricas nos dicen qué tan bien predice la calificación de un restaurante:

- **RMSE** (Root Mean Squared Error): error promedio en unidades de estrellas. Más bajo = mejor.
- **MAE** (Mean Absolute Error): error absoluto promedio. Más interpretable que RMSE.
- **R²**: qué fracción de la variabilidad en el rating explica el modelo. 1.0 es perfecto.

"""

def evaluate_model(name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    mae  = mean_absolute_error(y_test, y_pred)
    r2   = r2_score(y_test, y_pred)

    print(f'\n--- Resultados {name} ---')
    print(f'Mejores Hiperparámetros: {model.best_params_}')
    print(f'RMSE    : {rmse:.4f}  (error en estrellas)')
    print(f'MAE     : {mae:.4f}  (error absoluto medio)')
    print(f'R²      : {r2:.4f}  (varianza explicada)')
    return y_pred, rmse, mae, r2

pred_ridge, rmse_ridge, mae_ridge, r2_ridge = evaluate_model(
    'Ridge (GridSearch)', grid_search_ridge, X_test, y_test)

pred_rf, rmse_rf, mae_rf, r2_rf = evaluate_model(
    'Random Forest (RandomSearch)', random_search_rf, X_test, y_test)

# ── Scatter: Real vs Predicho ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for ax, pred, name, color in zip(
    axes,
    [pred_ridge, pred_rf],
    ['Ridge Regression', 'Random Forest'],
    ['steelblue', 'seagreen']
):
    ax.scatter(y_test, pred, alpha=0.3, color=color, s=15)
    ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=1.5)
    ax.set_title(f'{name}: Real vs Predicho')
    ax.set_xlabel('Calificación Real (rate)')
    ax.set_ylabel('Calificación Predicha')
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 14. Comparación cruzada: No Supervisado vs Supervisado

Esta sección responde la pregunta central: **¿qué nos aportó cada enfoque?**

Los dos enfoques no compiten entre sí — responden preguntas distintas sobre los mismos datos.

"""

print('=' * 60)
print('RESUMEN COMPARATIVO FINAL')
print('=' * 60)

print('\n── APRENDIZAJE NO SUPERVISADO (Clustering) ──')
print(metricas_ns.to_string())

print('\n── APRENDIZAJE SUPERVISADO (Regresión) ──')
metricas_sup = pd.DataFrame({
    'Modelo': ['Ridge Regression', 'Random Forest'],
    'RMSE':   [round(rmse_ridge, 4), round(rmse_rf, 4)],
    'MAE':    [round(mae_ridge,  4), round(mae_rf,  4)],
    'R²':     [round(r2_ridge,   4), round(r2_rf,   4)],
}).set_index('Modelo')
print(metricas_sup.to_string())

# ── Visualización comparativa ────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# Panel izquierdo: métricas no supervisado
metodos_ns = ['K-Means', 'Jerárquico']
sil_vals_ns = [sil_km, sil_agg]
axes[0].bar(metodos_ns, sil_vals_ns, color=['steelblue', 'darkorange'])
axes[0].set_title('No Supervisado — Silhouette Score\n(↑ mejor separación de clusters)')
axes[0].set_ylabel('Silhouette Score')
for i, v in enumerate(sil_vals_ns):
    axes[0].text(i, v - 0.005, f'{v:.4f}', ha='center', va='top',
                 color='white', fontweight='bold', fontsize=10)
axes[0].set_ylim(0, max(sil_vals_ns) * 1.2)
axes[0].grid(True, alpha=0.3, axis='y')

# Panel derecho: R² supervisado
modelos_sup = ['Ridge', 'Random Forest']
r2_vals = [r2_ridge, r2_rf]
colores_sup = ['royalblue', 'seagreen']
axes[1].bar(modelos_sup, r2_vals, color=colores_sup)
axes[1].set_title('Supervisado — R² Score\n(↑ mejor poder predictivo)')
axes[1].set_ylabel('R² Score')
for i, v in enumerate(r2_vals):
    axes[1].text(i, v - 0.01, f'{v:.4f}', ha='center', va='top',
                 color='white', fontweight='bold', fontsize=10)
axes[1].set_ylim(0, 1.0)
axes[1].grid(True, alpha=0.3, axis='y')

plt.suptitle('Comparación final: enfoques no supervisado vs supervisado', fontsize=13)
plt.tight_layout()
plt.show()

print('\n── ¿QUÉ NOS DIO CADA ENFOQUE? ──')
print("""
No Supervisado (Clustering):
  → Descubrió grupos naturales de restaurantes sin usar 'rate'.
  → Útil para segmentación de mercado y estrategia comercial.
  → No predice valores, describe patrones.

Supervisado (Regresión):
  → Aprendió a predecir la calificación de un restaurante nuevo.
  → Útil para recomendar acciones que mejoren el rating.
  → Requiere datos etiquetados (conocer 'rate' en el entrenamiento).

Ambos enfoques son complementarios: el clustering segmenta,
la regresión predice. Juntos ofrecen una visión completa del negocio.
""")

"""## Resumen final

| Etapa | Enfoque | Técnica | Métrica clave |
|---|---|---|---|
| PCA | No supervisado | Reducción de dimensionalidad | 95% varianza retenida |
| K-Means | No supervisado | Clustering optimizado | Silhouette Score |
| Jerárquico | No supervisado | Agglomerative Ward | Silhouette Score |
| Ridge | Supervisado | Regresión lineal regularizada | R², RMSE |
| Random Forest | Supervisado | Ensemble de árboles | R², RMSE |

**Conclusión:** Los segmentos encontrados por el clustering pueden usarse como feature adicional en el modelo supervisado, potencialmente mejorando su capacidad predictiva en una iteración futura.

"""